# Generated by Django 4.2.13 on 2024-06-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=180)),
                ('deckname', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_word', models.CharField(max_length=180)),
                ('second_word', models.CharField(max_length=180)),
                ('third_word', models.CharField(max_length=180, null=True)),
                ('fourth_word', models.CharField(max_length=180, null=True)),
                ('main_word', models.CharField(max_length=180)),
                ('deck', models.ManyToManyField(to='api.deck')),
            ],
        ),
    ]
