# Generated by Django 4.2.13 on 2024-08-01 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deckname', models.CharField(max_length=180)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_word', models.CharField(max_length=180)),
                ('second_word', models.CharField(max_length=180)),
                ('third_word', models.CharField(max_length=180, null=True)),
                ('fourth_word', models.CharField(max_length=180, null=True)),
                ('main_word', models.CharField(max_length=180)),
                ('deck', models.ManyToManyField(to='api.deck')),
            ],
        ),
    ]
